# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as mp

2. Create a null vector of size 10 

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(x.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [11]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda\\Library\\include']

7. Print the dimension of the array in question 3


In [14]:
x = np.arange(10,50)
x.ndim

1

8. Create a boolean array with all the True values

In [15]:
bool_arr = np.array([1,2,3,4,5,6], dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True]


9. Create a two dimensional array




In [16]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [17]:
y = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
x = np.arange(25)
x = x[::-1]
x

12. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [19]:
y = np.identity(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [20]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype('float64')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [21]:
arr1 = np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [22]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)

False


17. Extract all odd numbers from arr with values(0-9)

In [23]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [24]:
b = np.array([0,1,2,3,4,5,6,7,8,9])
-b[b%2 == 1]

array([-1, -3, -5, -7, -9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [25]:
p=np.arange(0,14)
p[5:9] = 12
p

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13])

20. Create a 2d array with 1 on the border and 0 inside

In [26]:
y = np.ones((10,10))
y[1:-1,1:-1] = 0
y

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [27]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [30]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [31]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:3:2,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [2]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
z = np.random.randint((10,10))
a = [10,7,5]
b = [6,4,2]
print('random numbers are ',z)
print(z.max())
print(z.min())

random numbers are  [1 2]
2
1


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
R = np.intersect1d(a,b)
R


array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names != "will"]

array([[-0.13397146,  0.04283697, -1.78441344,  0.27183022],
       [-1.01298717, -0.6192501 ,  0.2681939 , -0.93201493],
       [-0.47132573,  0.36975072,  0.41100247,  2.49670587],
       [ 0.91742935,  0.06153542,  1.94687737,  0.16091526],
       [-0.88981225,  0.04074889, -0.65627596, -0.49044949],
       [ 0.75393464,  0.40398347, -0.87875158,  1.8531569 ],
       [ 0.03249754,  0.54759276, -0.65437813,  0.15230072]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
print(data[names != "will"])
print(data[names != "Joe"])

[[ 0.51943914 -0.71533949 -1.69831812 -0.23688046]
 [-0.20889087 -0.9168474  -0.15960777 -0.25969824]
 [-0.07439387 -1.80786308 -0.21542929 -0.85260293]
 [ 1.54294227  0.96483586 -0.08752342  0.42790632]
 [-0.11196694 -1.05889449  0.30463837 -0.62058324]
 [-0.81749947 -1.50510725 -1.35813171 -0.04667486]
 [ 0.91839197 -2.54060464  0.79121987  1.09018827]]
[[ 0.51943914 -0.71533949 -1.69831812 -0.23688046]
 [-0.07439387 -1.80786308 -0.21542929 -0.85260293]
 [ 1.54294227  0.96483586 -0.08752342  0.42790632]
 [-0.11196694 -1.05889449  0.30463837 -0.62058324]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
arr = np.random.randn(1,15).reshape(5,3)
arr

array([[ 1.96408839,  0.47655144,  0.59630472],
       [ 0.80189544, -0.72915798,  0.31229751],
       [ 0.40980613, -0.89995774, -0.39799616],
       [ 0.48546405, -0.00742209,  0.2381966 ],
       [ 0.74334036, -0.72814447, -0.40985661]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
arr = np.random.randn(1,16).reshape(2,2,4)
arr

array([[[-0.38447163,  0.20296344, -1.40276318, -1.45483305],
        [ 0.39496542, -0.51197845,  0.9799359 , -1.1925956 ]],

       [[-0.25974429, -0.20772949,  0.64354785,  0.31724754],
        [-0.29953614,  0.65474592,  1.24624704,  0.99034593]]])

33. Swap axes of the array you created in Question 32

In [39]:
arr = np.random.randn(1,16).reshape(2,2,4)
data.T

array([[ 0.51943914, -0.20889087, -0.07439387,  1.54294227, -0.11196694,
        -0.81749947,  0.91839197],
       [-0.71533949, -0.9168474 , -1.80786308,  0.96483586, -1.05889449,
        -1.50510725, -2.54060464],
       [-1.69831812, -0.15960777, -0.21542929, -0.08752342,  0.30463837,
        -1.35813171,  0.79121987],
       [-0.23688046, -0.25969824, -0.85260293,  0.42790632, -0.62058324,
        -0.04667486,  1.09018827]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
P = np.arange(10)
P = np.sqrt(R)
np.where(P<0.5,0,P)

array([1.41421356, 2.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
a = np.random.randn(12)
b = np.random.randn(12)
np. maximum(a,b)

array([-0.47953315,  0.1926125 ,  0.2149294 , -0.49055205, -0.5367261 ,
        0.78454637,  1.36251795,  0.79643594,  1.43856655,  0.78155771,
        1.12655528,  0.59619347])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = set(names)
names

{'Bob', 'Joe', 'Will'}

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [43]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray = np.delete(sampleArray,1,axis = 1)
sampleArray

array([[34, 73],
       [82, 12],
       [53, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
n = np.random.randn(20)
n.cumsum()

array([-0.4530499 , -1.31262546, -2.57398298, -2.6105688 , -2.48898558,
       -3.34882904, -2.42698239, -2.84219531, -3.24988435, -1.61425617,
       -1.12527214,  0.57416948,  0.65436684,  2.01105107,  2.86383018,
        2.92385665,  2.08485307,  1.11224395, -0.59615587, -0.0210812 ])